# Generated by Django 3.0.6 on 2020-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paslaugos_kaina',
            name='name',
        ),
    ]
