# Generated by Django 3.0.6 on 2020-05-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_remove_paslaugos_kaina_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klientas', models.CharField(max_length=200, verbose_name='Klientas')),
                ('suma', models.FloatField(verbose_name='Suma')),
                ('automobilis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('paslauga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Paslauga')),
                ('uzsakymas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Eilutės', to='autoservice.Uzsakymas')),
            ],
        ),
    ]
