# Generated by Django 3.0.6 on 2020-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_uzsakymoeilute_kiekis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paslaugos_kaina',
            name='automobilis_id',
        ),
        migrations.AddField(
            model_name='paslaugos_kaina',
            name='automobiliai_ids',
            field=models.ManyToManyField(to='autoservice.Automobilis'),
        ),
    ]
